export enum EstimateAgeStep {
    None = "NONE",
    Consent = "CONSENT",
    PreEnroll = "PRE_ENROLL",
    Enroll = "ENROLL",
    AgeScan = "AGE_SCAN",
    DocumentTypeSelection = "DOCUMENT_TYPE_SELECTION",
    PreFrontDlScan = "PRE_FRONT_DL_SCAN",
    FrontDlScan = "FRONT_DL_SCAN",
    PreBacktDlScan = "PRE_BACK_DL_SCAN",
    BackDlScan = "BACK_DL_SCAN",
    PrePassportScan = "PRE_PASSPORT_SCAN",
    PassportScan = "PASSPORT SCAN",
    Passkey = "PASSKEY",
    Success = "SUCCESS",
    Failure = "FAILURE",
  };

export enum RegistrationStep {
    None = "NONE",
    Consent = "CONSENT",
    PreEnroll = "PRE_ENROLL",
    Enroll = "ENROLL",
    DocumentTypeSelection = "DOCUMENT_TYPE_SELECTION",
    PreFrontDlScan = "PRE_FRONT_DL_SCAN",
    FrontDlScan = "FRONT_DL_SCAN",
    PreBacktDlScan = "PRE_BACK_DL_SCAN",
    BackDlScan = "BACK_DL_SCAN",
    PrePassportScan = "PRE_PASSPORT_SCAN",
    PassportScan = "PASSPORT SCAN",
    Passkey = "PASSKEY",
    Success = "SUCCESS",
    Failure = "FAILURE",
  };

export enum AuthenticationSteps {
    None = "NONE",
    Consent = "CONSENT",
    DocumentTypeSelection = "DOCUMENT_TYPE_SELECTION",
    PreFrontDlScan = "PRE_FRONT_DL_SCAN",
    FrontDlScan = "FRONT_DL_SCAN",
    PreBacktDlScan = "PRE_BACK_DL_SCAN",
    BackDlScan = "BACK_DL_SCAN",
    PrePassportScan = "PRE_PASSPORT_SCAN",
    PassportScan = "PASSPORT SCAN",
    Passkey = "PASSKEY",
    Success = "SUCCESS",
    Failure = "FAILURE",
    FaceLogin = "FaceLogin",
  }