export const UrlJSON = {
    None: "/",
    AgeScan: "AGE_SCAN",
    FaceLogin: "/face-login",
    FaceLoginWithPasskey: "/login-passkey",
    RegistrationConsent: "/identity-consent",
    LoginConsent: "/user-consent",
    PersonalInfo: "/user-info",
    PreEnroll: "/face-scan-intro",
    Enroll: "/face-scan",
    DocumentTypeSelection: "/doc-selection",
    PreFrontDlScan: "/drivers-licence-intro",
    FrontDlScan: "/front-dl-scan",
    PrePassportScan: "/passport-scan-intro",
    PassportScan: "/passport-scan",
    PreBacktDlScan: "/drivers-licence-back-intro",
    BackDlScan: "/back-dl-scan",
    GeneratePasskey: "/generate-passkey",
    Pin: "/verify-pin",
    Success: "/success",
    Failure: "/failure",
    NotApproved: "/not-approved",
    Ssn: "/ssn",
    Address: "/address",
    Waiting: "/waiting",
}
