name: oidc-client devel privateid workflow

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to deploy'
        required: true
        type: string
  
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SKIP_PREFLIGHT_CHECK: true
      REACT_APP_API_URL: https://api.orchestration.private.id/oidc
      REACT_APP_CLIENT_ID: A1sq0HVPNLhgpTCwRl_ut
      REACT_APP_PRODUCT_GROUP_ID: test101
      REACT_APP_OIDC_AUTH_URL: https://oidc.privateid.com/auth
      REACT_APP_OIDC_TOKEN_URL: https://oidc.privateid.com/token
      REACT_APP_REDIRECT_URL: https://oidc-ui.devel.privateid.com
      CI: false

    steps:
        - uses: actions/checkout@v1
          with:
            ref: ${{ inputs.commit_sha }}

        - name: Install dependencies
          run: yarn install

        - name: Build
          run: yarn build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: / *
