name: oidc-client devel privateid workflow

on:
  push:
    branches:
    - devel
  
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SKIP_PREFLIGHT_CHECK: true
      REACT_APP_API_URL: https://api.orchestration.devel.privateid.com/oidc
      REACT_APP_OIDC_AUTHORITY: https://oidc.devel.privateid.com/.well-known/openid-configuration
      # REACT_APP_CLIENT_ID: qLgLQvu-_lNwGFLqTe1g6
      # REACT_APP_CLIENT_SECRET: 2If6Z8YGABYn7BRObpnWXWdSjbO2ufePtznXMfYm0t2sZ6sRnPO9PtJ6FBZtB8FYaRKfT3rRdQOzamdtFFYlwg
      REACT_APP_OIDC_URL: https://oidc.devel.privateid.com
      REACT_APP_CLIENT_ID: 0nCeaqMLNuIhZ2nFV029i
      #REACT_APP_CLIENT_ID: CtzBXSfip7saYUGB28gps
      REACT_APP_CLIENT_SECRET: IWTPqmKF2W_jE3gLzONcjSxbqDbIuazQQ1ZsHLXyTKYCg17eD6E0WoWoN6tEaDPeb5XEU6K44vE_H9NFZ0UYaQ
      REACT_APP_AUTH_PRODUCT_GROUP_ID: test102
      REACT_APP_PRODUCT_GROUP_ID: test101
      REACT_APP_OIDC_AUTH_URL: https://oidc.devel.privateid.com/auth
      REACT_APP_OIDC_TOKEN_URL: https://oidc.devel.privateid.com/token
      REACT_APP_OIDC_REDIRECT_URL: https://oidc-ui.devel.privateid.com/callback
      REACT_APP_REDIRECT_URL: https://oidc-ui.devel.privateid.com
      CI: false

    steps:
        - uses: actions/checkout@v1
          with:
            ref: ${{ inputs.commit_sha }}

        - name: Install dependencies
          run: yarn install

        - name: Build
          run: yarn build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: / *
